# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WindFarmLayout
                                 A QGIS plugin
 This plugin uses NEWA data to build an optimal layout for an onshore wind farm in areas covered by NEWA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-21
        git sha              : $Format:%H$
        copyright            : (C) 2025 by Pranav Joshi
        email                : pranavjoshi232@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
# -*- coding: utf-8 -*-
from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon
from .wind_farm_dialog import WindFarmDialog
from qgis.PyQt.QtCore import Qt

class WindFarmLayout:
    """Dialog-based plugin wrapper."""

    def __init__(self, iface):
        self.iface = iface
        self.dialog = None
        self.action = None

    def initGui(self):
        icon_path = ':/plugins/layout_builder/icon.png'
        self.action = QAction(QIcon(icon_path), "Layout Builder for Onshore Windfarms", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addPluginToVectorMenu("Layout Builder for Onshore Windfarms", self.action)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        self.iface.removePluginVectorMenu("Layout Builder for Onshore Windfarms", self.action)
        self.iface.removeToolBarIcon(self.action)

    def run(self):
        if self.dialog is None:
            self.dialog = WindFarmDialog()
        self.dialog.show()
        self.dialog.raise_()
        self.dialog.activateWindow()
