# -*- coding: utf-8 -*-
"""
/***************************************************************************
 WindFarmLayout
                                 A QGIS plugin
 This plugin uses NEWA data to build an optimal layout for an onshore wind farm in areas covered by NEWA
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-08-21
        copyright            : (C) 2025 by Pranav Joshi
        email                : pranavjoshi232@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load WindFarmLayout class from file WindFarmLayout.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .layout_builder import WindFarmLayout
    return WindFarmLayout(iface)
