# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wind_farm_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WFDialog(object):
    def setupUi(self, WFDialog):
        WFDialog.setObjectName("WFDialog")
        WFDialog.resize(452, 308)
        self.buttonBox = QtWidgets.QDialogButtonBox(WFDialog)
        self.buttonBox.setGeometry(QtCore.QRect(100, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.lat_input = QtWidgets.QLineEdit(WFDialog)
        self.lat_input.setGeometry(QtCore.QRect(70, 10, 91, 20))
        self.lat_input.setObjectName("lat_input")
        self.lon_input = QtWidgets.QLineEdit(WFDialog)
        self.lon_input.setGeometry(QtCore.QRect(180, 10, 91, 20))
        self.lon_input.setDragEnabled(True)
        self.lon_input.setObjectName("lon_input")
        self.coord_layer_combo = QgsMapLayerComboBox(WFDialog)
        self.coord_layer_combo.setGeometry(QtCore.QRect(110, 40, 160, 20))
        self.coord_layer_combo.setObjectName("coord_layer_combo")
        self.rotor_diameter_input = QtWidgets.QLineEdit(WFDialog)
        self.rotor_diameter_input.setGeometry(QtCore.QRect(110, 70, 91, 20))
        self.rotor_diameter_input.setObjectName("rotor_diameter_input")
        self.grid_spacing_input = QtWidgets.QLineEdit(WFDialog)
        self.grid_spacing_input.setGeometry(QtCore.QRect(310, 70, 121, 20))
        self.grid_spacing_input.setObjectName("grid_spacing_input")
        self.Spacing_label = QtWidgets.QLabel(WFDialog)
        self.Spacing_label.setGeometry(QtCore.QRect(220, 70, 81, 20))
        self.Spacing_label.setObjectName("Spacing_label")
        self.D_label = QtWidgets.QLabel(WFDialog)
        self.D_label.setGeometry(QtCore.QRect(10, 70, 101, 20))
        self.D_label.setObjectName("D_label")
        self.Cord_label = QtWidgets.QLabel(WFDialog)
        self.Cord_label.setGeometry(QtCore.QRect(10, 10, 61, 20))
        self.Cord_label.setObjectName("Cord_label")
        self.use_point_layer_chk = QtWidgets.QCheckBox(WFDialog)
        self.use_point_layer_chk.setGeometry(QtCore.QRect(10, 40, 101, 20))
        self.use_point_layer_chk.setObjectName("use_point_layer_chk")
        self.construction_layer_combo = QgsMapLayerComboBox(WFDialog)
        self.construction_layer_combo.setGeometry(QtCore.QRect(120, 100, 160, 20))
        self.construction_layer_combo.setObjectName("construction_layer_combo")
        self.PolygonInput = QtWidgets.QLabel(WFDialog)
        self.PolygonInput.setGeometry(QtCore.QRect(10, 100, 101, 20))
        self.PolygonInput.setObjectName("PolygonInput")
        self.export_wakes_chk = QtWidgets.QCheckBox(WFDialog)
        self.export_wakes_chk.setGeometry(QtCore.QRect(300, 100, 131, 20))
        self.export_wakes_chk.setObjectName("export_wakes_chk")
        self.progress_bar = QtWidgets.QProgressBar(WFDialog)
        self.progress_bar.setGeometry(QtCore.QRect(10, 230, 441, 23))
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.itterations_slider = QtWidgets.QSlider(WFDialog)
        self.itterations_slider.setGeometry(QtCore.QRect(120, 130, 160, 20))
        self.itterations_slider.setMinimum(1)
        self.itterations_slider.setMaximum(50)
        self.itterations_slider.setOrientation(QtCore.Qt.Horizontal)
        self.itterations_slider.setInvertedAppearance(False)
        self.itterations_slider.setInvertedControls(False)
        self.itterations_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.itterations_slider.setObjectName("itterations_slider")
        self.label = QtWidgets.QLabel(WFDialog)
        self.label.setGeometry(QtCore.QRect(20, 130, 81, 20))
        self.label.setObjectName("label")
        self.init_wind_btn = QtWidgets.QPushButton(WFDialog)
        self.init_wind_btn.setGeometry(QtCore.QRect(10, 190, 111, 20))
        self.init_wind_btn.setObjectName("init_wind_btn")
        self.genrate_layout_btn = QtWidgets.QPushButton(WFDialog)
        self.genrate_layout_btn.setGeometry(QtCore.QRect(130, 190, 91, 20))
        self.genrate_layout_btn.setObjectName("genrate_layout_btn")
        self.plot_wind_btn = QtWidgets.QPushButton(WFDialog)
        self.plot_wind_btn.setGeometry(QtCore.QRect(230, 190, 91, 20))
        self.plot_wind_btn.setObjectName("plot_wind_btn")

        self.retranslateUi(WFDialog)
        self.buttonBox.accepted.connect(WFDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(WFDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(WFDialog)

    def retranslateUi(self, WFDialog):
        _translate = QtCore.QCoreApplication.translate
        WFDialog.setWindowTitle(_translate("WFDialog", "Dialog"))
        self.lat_input.setPlaceholderText(_translate("WFDialog", "Lattitude"))
        self.lon_input.setPlaceholderText(_translate("WFDialog", "Longitude"))
        self.coord_layer_combo.setPlaceholderText(_translate("WFDialog", "Select Coordinate Layer"))
        self.grid_spacing_input.setPlaceholderText(_translate("WFDialog", "Reccomended: 10"))
        self.Spacing_label.setText(_translate("WFDialog", "Grid Spacing (m):"))
        self.D_label.setText(_translate("WFDialog", "Rotor Diameter (m):"))
        self.Cord_label.setText(_translate("WFDialog", "Cordinates:"))
        self.use_point_layer_chk.setText(_translate("WFDialog", "Use Point Layer"))
        self.construction_layer_combo.setPlaceholderText(_translate("WFDialog", "Select Polygon Layer"))
        self.PolygonInput.setText(_translate("WFDialog", "Construction Areas:"))
        self.export_wakes_chk.setText(_translate("WFDialog", "Export Turbine Wakes"))
        self.label.setText(_translate("WFDialog", "Itterations"))
        self.init_wind_btn.setText(_translate("WFDialog", "Initialise Wind Data"))
        self.genrate_layout_btn.setText(_translate("WFDialog", "Generate Layout"))
        self.plot_wind_btn.setText(_translate("WFDialog", "Plot Wind Rose"))
from qgsmaplayercombobox import QgsMapLayerComboBox
